//! BPF program management module

use anyhow::{anyhow, Context, Result};
use libbpf_rs::{
    Link, MapCore, MapFlags,
};
use log::{debug, info, warn};
use std::collections::HashMap;
use std::mem::MaybeUninit;
use std::os::fd::AsFd;
use std::path::Path;
use std::fs;

use crate::types::*;

/// XDP skeleton module (generated by build.rs)
#[path = "../bpf/.output/xdp_policy.skel.rs"]
mod xdp_policy_skel;
use xdp_policy_skel::*;

/// BPF pinning directory
const BPF_PIN_PATH: &str = "/sys/fs/bpf/policy_engine";

/// Trait for skeleton opening (libbpf-rs 0.24 API)
use libbpf_rs::skel::{OpenSkel, SkelBuilder};

/// XDP attach flags
pub mod xdp_flags {
    pub const XDP_FLAGS_SKB_MODE: u32 = 1 << 1;
    pub const XDP_FLAGS_HW_MODE: u32 = 1 << 3;
}

/// State of an attached XDP program
pub struct XdpAttachment {
    _link: Option<Link>,
}

/// BPF program manager
pub struct BpfManager {
    xdp_skel: Option<XdpPolicySkel<'static>>,
    xdp_attachments: HashMap<i32, XdpAttachment>,
}

impl BpfManager {
    /// Create a new BPF manager (programs are loaded lazily on first use)
    pub fn new() -> Result<Self> {
        Ok(Self {
            xdp_skel: None,
            xdp_attachments: HashMap::new(),
        })
    }

    /// Load BPF programs (called lazily when needed)
    pub fn load_programs(&mut self) -> Result<()> {
        // Skip if already loaded
        if self.xdp_skel.is_some() {
            return Ok(());
        }

        debug!("Loading BPF programs...");

        // Load XDP skeleton
        // We use Box::leak to create 'static storage for the OpenObject
        let xdp_builder = XdpPolicySkelBuilder::default();
        let xdp_obj_storage: &'static mut MaybeUninit<libbpf_rs::OpenObject> = 
            Box::leak(Box::new(MaybeUninit::uninit()));
        let mut xdp_open = xdp_builder
            .open(xdp_obj_storage)
            .context("Failed to open XDP skeleton")?;

        // Try to reuse existing pinned maps
        self.try_reuse_pinned_maps(&mut xdp_open)?;

        let mut xdp_skel = xdp_open.load().context("Failed to load XDP program")?;

        // Pin the programs for persistence (on first load or after reload)
        self.pin_programs(&mut xdp_skel)?;

        debug!("BPF programs loaded successfully");

        self.xdp_skel = Some(xdp_skel);
        Ok(())
    }

    /// Try to reuse existing pinned maps for persistence across invocations
    fn try_reuse_pinned_maps(&self, open_skel: &mut OpenXdpPolicySkel) -> Result<()> {
        let pin_path = BPF_PIN_PATH;

        // List of maps to try reusing
        let map_reuses = [
            ("policy_rules", &mut open_skel.maps.policy_rules),
            ("rule_stats", &mut open_skel.maps.rule_stats),
            ("global_stats", &mut open_skel.maps.global_stats),
            ("ethertype_stats", &mut open_skel.maps.ethertype_stats),
            ("xdp_dispatcher", &mut open_skel.maps.xdp_dispatcher),
            ("events", &mut open_skel.maps.events),
            ("pkt_scratch", &mut open_skel.maps.pkt_scratch),
            ("default_action", &mut open_skel.maps.default_action),
            ("lpm_rules_v4", &mut open_skel.maps.lpm_rules_v4),
            ("lpm_rules_v6", &mut open_skel.maps.lpm_rules_v6),
        ];

        for (name, map) in map_reuses {
            let map_path = format!("{}/{}", pin_path, name);
            if Path::new(&map_path).exists() {
                match map.reuse_pinned_map(&map_path) {
                    Ok(()) => debug!("Reusing pinned map: {}", name),
                    Err(e) => {
                        warn!("Failed to reuse pinned map {}: {}, will create new", name, e);
                        // Remove stale pin
                        let _ = fs::remove_file(&map_path);
                    }
                }
            }
        }

        Ok(())
    }

    /// Pin BPF programs to the filesystem for persistence (skips already pinned items)
    fn pin_programs(&self, skel: &mut XdpPolicySkel) -> Result<()> {
        let pin_path = BPF_PIN_PATH;
        
        // Create the pin directory if it doesn't exist
        let path = Path::new(pin_path);
        if !path.exists() {
            std::fs::create_dir_all(path)
                .context("Failed to create BPF pin directory")?;
        }

        // Helper to pin only if not already pinned
        macro_rules! pin_if_needed {
            ($item:expr, $name:expr) => {
                let pin_file = format!("{}/{}", pin_path, $name);
                if !Path::new(&pin_file).exists() {
                    if let Err(e) = $item.pin(&pin_file) {
                        debug!("Failed to pin {}: {}", $name, e);
                    }
                }
            };
        }

        // Pin maps (only if not already pinned via reuse)
        pin_if_needed!(skel.maps.policy_rules, "policy_rules");
        pin_if_needed!(skel.maps.rule_stats, "rule_stats");
        pin_if_needed!(skel.maps.global_stats, "global_stats");
        pin_if_needed!(skel.maps.ethertype_stats, "ethertype_stats");
        pin_if_needed!(skel.maps.xdp_dispatcher, "xdp_dispatcher");
        pin_if_needed!(skel.maps.events, "events");
        pin_if_needed!(skel.maps.pkt_scratch, "pkt_scratch");
        pin_if_needed!(skel.maps.default_action, "default_action");
        pin_if_needed!(skel.maps.lpm_rules_v4, "lpm_rules_v4");
        pin_if_needed!(skel.maps.lpm_rules_v6, "lpm_rules_v6");

        // Pin programs (only if not already pinned)
        pin_if_needed!(skel.progs.xdp_policy_main, "xdp_policy_main");
        pin_if_needed!(skel.progs.xdp_nat, "xdp_nat");

        debug!("BPF programs and maps pinned to {}", pin_path);
        Ok(())
    }

    /// Get the pin path for an XDP link on an interface
    fn get_link_pin_path(ifname: &str) -> String {
        format!("{}/xdp_link_{}", BPF_PIN_PATH, ifname)
    }

    /// Get all pinned XDP attachments (for show interfaces command)
    pub fn get_pinned_attachments(filter_ifname: Option<&str>) -> Vec<(String, i32, String)> {
        let mut attachments = Vec::new();

        // Check all interfaces for active XDP programs by querying the kernel
        if let Ok(entries) = fs::read_dir("/sys/class/net") {
            for entry in entries.flatten() {
                if let Ok(name) = entry.file_name().into_string() {
                    // If a filter was provided, skip non-matching interfaces early
                    if let Some(filter) = filter_ifname {
                        if name != filter {
                            continue;
                        }
                    }

                    // Get ifindex
                    if let Ok(ifindex) = Self::get_ifindex(&name) {
                        // Query XDP status using bpf_xdp_query
                        let mut opts: libbpf_sys::bpf_xdp_query_opts = unsafe { std::mem::zeroed() };
                        opts.sz = std::mem::size_of::<libbpf_sys::bpf_xdp_query_opts>() as u64;

                        unsafe {
                            let res = libbpf_sys::bpf_xdp_query(ifindex, 0, &mut opts);
                            if res == 0 && opts.prog_id != 0 {
                                // Found an attached program
                                debug!("Interface {} XDP query: prog_id={}, attach_mode={}, drv_prog_id={}, skb_prog_id={}, hw_prog_id={} ", 
                                    name, opts.prog_id, opts.attach_mode, opts.drv_prog_id, opts.skb_prog_id, opts.hw_prog_id);

                                let mode_str = match opts.attach_mode {
                                    1 => "native",
                                    2 => "generic",
                                    3 => "offload",
                                    _ => "unknown",
                                };
                                attachments.push((name, ifindex, mode_str.to_string()));
                            }
                        }
                    }
                }
            }
        }

        attachments
    }

    /// Get the mode metadata directory (use /var/run/policy_engine)
    fn get_mode_dir() -> &'static str {
        "/var/run/policy_engine"
    }

    /// Get the pin path for mode metadata
    fn get_mode_pin_path(ifname: &str) -> String {
        format!("{}/xdp_mode_{}", Self::get_mode_dir(), ifname)
    }

    /// Ensure mode directory exists
    fn ensure_mode_dir() {
        let _ = fs::create_dir_all(Self::get_mode_dir());
    }

    /// Store XDP mode metadata when pinning a link
    fn store_xdp_mode(ifname: &str, mode: XdpMode) {
        Self::ensure_mode_dir();
        
        let mode_path = Self::get_mode_pin_path(ifname);
        let mode_str = match mode {
            XdpMode::Unspec => "unspec",
            XdpMode::Native => "native",
            XdpMode::Generic => "skb",
            XdpMode::Offload => "hw",
        };
        
        // Store in /var/run which is usually writable
        let _ = fs::write(&mode_path, mode_str);
    }

    /// Remove XDP mode metadata when unpinning
    fn remove_xdp_mode(ifname: &str) {
        let mode_path = Self::get_mode_pin_path(ifname);
        let _ = fs::remove_file(&mode_path);
    }

    /// Clean up all pinned BPF maps and programs
    /// Called when no more interfaces are attached
    fn cleanup_pinned_bpf() {
        let pin_path = Path::new(BPF_PIN_PATH);
        if pin_path.exists() {
            // Remove all pinned files in the directory
            if let Ok(entries) = fs::read_dir(pin_path) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if path.is_file() {
                        debug!("Removing pinned BPF object: {:?}", path);
                        let _ = fs::remove_file(&path);
                    }
                }
            }
            // Try to remove the directory itself
            let _ = fs::remove_dir(pin_path);
            info!("Cleaned up pinned BPF maps and programs from {}", BPF_PIN_PATH);
        }
    }

    /// Check if any XDP programs are still attached to any interface
    fn any_xdp_attached() -> bool {
        if let Ok(entries) = fs::read_dir("/sys/class/net") {
            for entry in entries.flatten() {
                if let Ok(name) = entry.file_name().into_string() {
                    if let Ok(ifindex) = Self::get_ifindex(&name) {
                        let mut opts: libbpf_sys::bpf_xdp_query_opts = unsafe { std::mem::zeroed() };
                        opts.sz = std::mem::size_of::<libbpf_sys::bpf_xdp_query_opts>() as u64;
                        
                        unsafe {
                            if libbpf_sys::bpf_xdp_query(ifindex as i32, 0, &mut opts) == 0 {
                                if opts.prog_id != 0 {
                                    return true;
                                }
                            }
                        }
                    }
                }
            }
        }
        false
    }

    /// Attach XDP program to an interface
    pub fn attach_xdp(&mut self, ifname: &str, mode: XdpMode) -> Result<()> {
        let ifindex = Self::get_ifindex(ifname)?;
        let link_path = Self::get_link_pin_path(ifname);

        // Ensure pin directory exists with write permissions
        let pin_dir = Path::new(BPF_PIN_PATH);
        if !pin_dir.exists() {
            std::fs::create_dir_all(pin_dir)
                .context("Failed to create BPF pin directory")?;
        }

        // Check if already attached via pinned link
        if Path::new(&link_path).exists() {
            match Link::open(&link_path) {
                Ok(_) => {
                    return Err(anyhow!(
                        "XDP program already attached to interface {} (pinned link exists)",
                        ifname
                    ));
                }
                Err(_) => {
                    // Stale pin, remove it
                    let _ = fs::remove_file(&link_path);
                }
            }
        }

        // Check if we have an in-memory attachment
        if self.xdp_attachments.contains_key(&ifindex) {
            return Err(anyhow!(
                "XDP program already attached to interface {}",
                ifname
            ));
        }

        let skel = self
            .xdp_skel
            .as_mut()
            .ok_or_else(|| anyhow!("XDP skeleton not loaded"))?;

        let prog = &skel.progs.xdp_policy_main;
        
        // Get the program FD to use with bpf_xdp_attach
        let prog_fd = std::os::unix::io::AsRawFd::as_raw_fd(&prog.as_fd());
        
        // Determine XDP flags based on mode
        let xdp_flags = match mode {
            XdpMode::Native => 0,
            XdpMode::Generic => xdp_flags::XDP_FLAGS_SKB_MODE,
            XdpMode::Offload => xdp_flags::XDP_FLAGS_HW_MODE,
            _ => 0,
        };
        
        // Attach with specific mode flags using bpf_xdp_attach (kernel does the actual attachment)
        unsafe {
            let res = libbpf_sys::bpf_xdp_attach(
                ifindex as i32,
                prog_fd,
                xdp_flags,
                std::ptr::null_mut(),
            );
            if res != 0 {
                return Err(anyhow!("Failed to attach XDP program: error code {}", res));
            }
        }

        // Store mode metadata for later retrieval
        // (The kernel manages the actual link persistence)
        Self::store_xdp_mode(ifname, mode);

        debug!("Attached XDP program via {} mode", mode);

        // Note: We don't create a libbpf-rs Link object here because we're using
        // direct kernel attachment via bpf_xdp_attach with mode-specific flags.
        // The kernel manages link persistence; we manage mode metadata in /var/run.

        info!(
            "Attached XDP program to {} (ifindex={}) in {:?} mode",
            ifname, ifindex, mode
        );

        self.xdp_attachments.insert(
            ifindex,
            XdpAttachment {
                _link: None,
            },
        );

        Ok(())
    }

    /// Detach XDP program from an interface
    pub fn detach_xdp(&mut self, ifname: &str) -> Result<()> {
        let ifindex = Self::get_ifindex(ifname)?;

        // First query to see which mode is attached
        let mut opts: libbpf_sys::bpf_xdp_query_opts = unsafe { std::mem::zeroed() };
        opts.sz = std::mem::size_of::<libbpf_sys::bpf_xdp_query_opts>() as u64;
        
        let detach_flags = unsafe {
            let res = libbpf_sys::bpf_xdp_query(ifindex as i32, 0, &mut opts);
            if res != 0 {
                return Err(anyhow!("Failed to query XDP mode before detach"));
            }
            
            // Determine which flags to use for detaching based on attach_mode
            match opts.attach_mode {
                1 => 0u32,  // native mode
                2 => xdp_flags::XDP_FLAGS_SKB_MODE,  // generic/skb mode
                3 => xdp_flags::XDP_FLAGS_HW_MODE,  // offload/hw mode
                _ => 0u32,  // unknown, try default
            }
        };

        // Use bpf_xdp_detach to remove the XDP program from the kernel
        unsafe {
            let res = libbpf_sys::bpf_xdp_detach(ifindex as i32, detach_flags, std::ptr::null_mut());
            if res != 0 && res != -2 {
                // -2 (ENOENT) is expected if no program is attached, which is fine
                return Err(anyhow!("Failed to detach XDP program: error code {}", res));
            }
        }

        // Remove from our in-memory state if present
        self.xdp_attachments.remove(&ifindex);

        // Remove mode metadata
        Self::remove_xdp_mode(ifname);

        info!("Detached XDP program from {} (ifindex={})", ifname, ifindex);

        // If no more interfaces have XDP attached, clean up all pinned BPF objects
        if !Self::any_xdp_attached() {
            Self::cleanup_pinned_bpf();
        }

        Ok(())
    }

    /// Add a policy rule
    pub fn add_rule(&mut self, key: &FlowKey, value: &PolicyValue) -> Result<()> {
        // Add to XDP map
        if let Some(skel) = &mut self.xdp_skel {
            let map = &skel.maps.policy_rules;
            map.update(key.as_bytes(), value.as_bytes(), MapFlags::ANY)
                .context("Failed to add rule to XDP policy map")?;
        }

        debug!("Added policy rule: {:?} -> {:?}", key, value);
        Ok(())
    }

    /// Delete a policy rule
    pub fn delete_rule(&mut self, key: &FlowKey) -> Result<()> {
        // Delete from XDP map
        if let Some(skel) = &mut self.xdp_skel {
            let map = &skel.maps.policy_rules;
            map.delete(key.as_bytes())
                .context("Failed to delete rule from XDP policy map")?;
        }


        debug!("Deleted policy rule: {:?}", key);
        Ok(())
    }

    /// Add an IPv4 LPM policy rule
    pub fn add_lpm_rule_v4(&mut self, key: &LpmKeyV4, value: &LpmPolicyEntry) -> Result<()> {
        if let Some(skel) = &mut self.xdp_skel {
            let map = &skel.maps.lpm_rules_v4;
            map.update(key.as_bytes(), value.as_bytes(), MapFlags::ANY)
                .context("Failed to add rule to LPM IPv4 map")?;
        }

        debug!("Added LPM IPv4 rule: {:?}", key);
        Ok(())
    }

    /// Add an IPv6 LPM policy rule
    pub fn add_lpm_rule_v6(&mut self, key: &LpmKeyV6, value: &LpmPolicyEntry) -> Result<()> {
        if let Some(skel) = &mut self.xdp_skel {
            let map = &skel.maps.lpm_rules_v6;
            map.update(key.as_bytes(), value.as_bytes(), MapFlags::ANY)
                .context("Failed to add rule to LPM IPv6 map")?;
        }

        debug!("Added LPM IPv6 rule: {:?}", key);
        Ok(())
    }

    /// Delete an IPv4 LPM policy rule
    pub fn delete_lpm_rule_v4(&mut self, key: &LpmKeyV4) -> Result<()> {
        if let Some(skel) = &mut self.xdp_skel {
            let map = &skel.maps.lpm_rules_v4;
            map.delete(key.as_bytes())
                .context("Failed to delete rule from LPM IPv4 map")?;
        }

        debug!("Deleted LPM IPv4 rule: {:?}", key);
        Ok(())
    }

    /// Delete an IPv6 LPM policy rule
    pub fn delete_lpm_rule_v6(&mut self, key: &LpmKeyV6) -> Result<()> {
        if let Some(skel) = &mut self.xdp_skel {
            let map = &skel.maps.lpm_rules_v6;
            map.delete(key.as_bytes())
                .context("Failed to delete rule from LPM IPv6 map")?;
        }

        debug!("Deleted LPM IPv6 rule: {:?}", key);
        Ok(())
    }

    /// List all IPv4 LPM policy rules
    pub fn list_lpm_rules_v4(&self) -> Result<Vec<(LpmKeyV4, LpmPolicyEntry)>> {
        let mut rules = Vec::new();

        if let Some(skel) = &self.xdp_skel {
            let map = &skel.maps.lpm_rules_v4;

            for key_bytes in map.keys() {
                let mut key = LpmKeyV4::default();
                plain::copy_from_bytes(&mut key, &key_bytes)
                    .map_err(|e| anyhow!("Failed to parse LPM key: {:?}", e))?;

                if let Some(value_bytes) = map.lookup(&key_bytes, MapFlags::ANY)? {
                    let mut value = LpmPolicyEntry::default();
                    plain::copy_from_bytes(&mut value, &value_bytes)
                        .map_err(|e| anyhow!("Failed to parse LPM value: {:?}", e))?;
                    rules.push((key, value));
                }
            }
        }

        Ok(rules)
    }

    /// List all IPv6 LPM policy rules
    pub fn list_lpm_rules_v6(&self) -> Result<Vec<(LpmKeyV6, LpmPolicyEntry)>> {
        let mut rules = Vec::new();

        if let Some(skel) = &self.xdp_skel {
            let map = &skel.maps.lpm_rules_v6;

            for key_bytes in map.keys() {
                let mut key = LpmKeyV6::default();
                plain::copy_from_bytes(&mut key, &key_bytes)
                    .map_err(|e| anyhow!("Failed to parse LPM key: {:?}", e))?;

                if let Some(value_bytes) = map.lookup(&key_bytes, MapFlags::ANY)? {
                    let mut value = LpmPolicyEntry::default();
                    plain::copy_from_bytes(&mut value, &value_bytes)
                        .map_err(|e| anyhow!("Failed to parse LPM value: {:?}", e))?;
                    rules.push((key, value));
                }
            }
        }

        Ok(rules)
    }

    /// List all policy rules
    pub fn list_rules(&self) -> Result<Vec<(FlowKey, PolicyValue)>> {
        let mut rules = Vec::new();

        if let Some(skel) = &self.xdp_skel {
            let map = &skel.maps.policy_rules;

            for key_bytes in map.keys() {
                let mut key = FlowKey::default();
                plain::copy_from_bytes(&mut key, &key_bytes)
                    .map_err(|e| anyhow!("Failed to parse key: {:?}", e))?;

                if let Some(value_bytes) = map.lookup(&key_bytes, MapFlags::ANY)? {
                    let mut value = PolicyValue::default();
                    plain::copy_from_bytes(&mut value, &value_bytes)
                        .map_err(|e| anyhow!("Failed to parse value: {:?}", e))?;
                    rules.push((key, value));
                }
            }
        }

        Ok(rules)
    }

    /// Get statistics for a rule
    pub fn get_rule_stats(&self, rule_id: u64) -> Result<Option<RuleStats>> {
        if let Some(skel) = &self.xdp_skel {
            let map = &skel.maps.rule_stats;
            let key_bytes = rule_id.to_ne_bytes();

            if let Some(value_bytes) = map.lookup(&key_bytes, MapFlags::ANY)? {
                let mut stats = RuleStats::default();
                plain::copy_from_bytes(&mut stats, &value_bytes)
                    .map_err(|e| anyhow!("Failed to parse stats: {:?}", e))?;
                return Ok(Some(stats));
            }
        }

        Ok(None)
    }

    /// Get global statistics for an interface
    pub fn get_global_stats(&self, ifindex: u32) -> Result<GlobalStats> {
        let mut total_stats = GlobalStats::default();
        let key = (ifindex % MAX_INTERFACES).to_ne_bytes();

        // Get XDP stats (per-CPU, need to aggregate)
        if let Some(skel) = &self.xdp_skel {
            let map = &skel.maps.global_stats;

            if let Some(values) = map.lookup_percpu(&key, MapFlags::ANY)? {
                for cpu_value in values {
                    let mut stats = GlobalStats::default();
                    plain::copy_from_bytes(&mut stats, &cpu_value)
                        .map_err(|e| anyhow!("Failed to parse stats: {:?}", e))?;

                    total_stats.rx_packets += stats.rx_packets;
                    total_stats.rx_bytes += stats.rx_bytes;
                    total_stats.policy_matches += stats.policy_matches;
                    total_stats.policy_drops += stats.policy_drops;
                    total_stats.policy_pass += stats.policy_pass;
                    total_stats.policy_redirects += stats.policy_redirects;
                    total_stats.parse_errors += stats.parse_errors;
                    total_stats.tail_calls += stats.tail_calls;
                    total_stats.bum_packets += stats.bum_packets;
                    total_stats.non_ip_unicast += stats.non_ip_unicast;
                }
            }
        }


        Ok(total_stats)
    }

    /// Get ethertype statistics for an interface
    pub fn get_ethertype_stats(&self, ifindex: u32) -> Result<Vec<EthertypeStats>> {
        let mut stats_map: std::collections::HashMap<u16, u64> = std::collections::HashMap::new();
        let ifindex_prefix = (ifindex % MAX_INTERFACES) << 16;

        if let Some(skel) = &self.xdp_skel {
            let map = &skel.maps.ethertype_stats;

            // Iterate through all keys in the map
            for key_bytes in map.keys() {
                if key_bytes.len() >= 4 {
                    let composite_key = u32::from_ne_bytes(key_bytes[..4].try_into().unwrap());
                    let key_ifindex = composite_key >> 16;
                    let ethertype = (composite_key & 0xFFFF) as u16;

                    // Only include entries for this interface
                    if (key_ifindex << 16) == ifindex_prefix {
                        // Aggregate per-CPU values
                        if let Some(values) = map.lookup_percpu(&key_bytes, MapFlags::ANY)? {
                            let mut total: u64 = 0;
                            for cpu_value in values {
                                if cpu_value.len() >= 8 {
                                    let count = u64::from_ne_bytes(cpu_value[..8].try_into().unwrap());
                                    total += count;
                                }
                            }
                            if total > 0 {
                                *stats_map.entry(ethertype).or_insert(0) += total;
                            }
                        }
                    }
                }
            }
        }

        // Convert to sorted Vec
        let mut result: Vec<EthertypeStats> = stats_map
            .into_iter()
            .map(|(ethertype, packets)| EthertypeStats { ethertype, packets })
            .collect();
        
        // Sort by packet count descending
        result.sort_by(|a, b| b.packets.cmp(&a.packets));

        Ok(result)
    }

    /// Set the default action for unmatched packets
    pub fn set_default_action(&mut self, action: PolicyAction) -> Result<()> {
        let key = 0u32.to_ne_bytes();
        let value = (action as u32).to_ne_bytes();

        if let Some(skel) = &mut self.xdp_skel {
            let map = &skel.maps.default_action;
            map.update(&key, &value, MapFlags::ANY)?;
        }


        info!("Set default action to {:?}", action);
        Ok(())
    }
    pub fn register_tail_call(&mut self, slot: u32, prog_name: &str) -> Result<()> {
        use std::os::fd::AsRawFd;
        
        if slot >= MAX_DISPATCHER_PROGS {
            return Err(anyhow!("Slot {} exceeds maximum {}", slot, MAX_DISPATCHER_PROGS));
        }

        if let Some(skel) = &mut self.xdp_skel {
            // Get the program by name
            let prog_fd = match prog_name {
                "nat" => skel.progs.xdp_nat.as_fd(),
                _ => return Err(anyhow!("Unknown program: {}", prog_name)),
            };

            let map = &skel.maps.xdp_dispatcher;
            let key = slot.to_ne_bytes();
            let fd = prog_fd.as_raw_fd().to_ne_bytes();
            map.update(&key, &fd, MapFlags::ANY)
                .context("Failed to register tail call")?;

            info!("Registered {} at dispatcher slot {}", prog_name, slot);
        }

        Ok(())
    }

    /// Get interface index from name
    fn get_ifindex(ifname: &str) -> Result<i32> {
        use std::ffi::CString;
        let name = CString::new(ifname)?;
        let ifindex = unsafe { libc::if_nametoindex(name.as_ptr()) };
        if ifindex == 0 {
            return Err(anyhow!("Interface {} not found", ifname));
        }
        Ok(ifindex as i32)
    }
}

impl Drop for BpfManager {
    fn drop(&mut self) {
        // XDP links are pinned to the filesystem, so they persist after this process exits.
        // We don't need to do anything special here - the links remain attached because
        // they're pinned, not because we're keeping file descriptors open.
        if self.xdp_skel.is_some() {
            debug!("BpfManager dropped, pinned BPF programs remain attached");
        }
    }
}
