// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Dufferin Software <support@dufferinsw.com>

//! CPU-affinity helpers for the policy-engine server.
//!
//! All OS-level calls live here; the rest of the crate stays pure and testable.
//!
//! The [`NicSysIo`] trait abstracts every `/proc` / `/sys` interaction so
//! tests can inject a mock without needing root or real network interfaces.
//! Production code uses [`DefaultNicSysIo`].

use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Thread pinning
// ---------------------------------------------------------------------------

/// Pin the calling thread to the first CPU in `cpus`.
///
/// Best-effort: logs a warning on failure but never panics.
pub fn pin_thread_to_cpus(cpus: &[usize]) {
    if let Some(&cpu) = cpus.first() {
        if !core_affinity::set_for_current(core_affinity::CoreId { id: cpu }) {
            log::warn!("cpu_affinity: failed to pin thread to CPU {cpu}");
        }
    }
}

/// Pin the calling thread to `cpus[index % cpus.len()]`.
///
/// Used from a tokio `on_thread_start` callback with an `AtomicUsize` counter
/// so consecutive Tokio workers are spread across `cpus` in round-robin order.
pub fn pin_thread_by_index(cpus: &[usize], index: usize) {
    if !cpus.is_empty() {
        pin_thread_to_cpus(&[cpus[index % cpus.len()]]);
    }
}

// ---------------------------------------------------------------------------
// NicSysIo trait — all /proc + /sys interactions
// ---------------------------------------------------------------------------

/// Abstracts every filesystem interaction needed by the NIC affinity helpers.
///
/// The real implementation is [`DefaultNicSysIo`].  Tests inject
/// [`MockNicSysIo`] (generated by `mockall` in test builds).
#[cfg_attr(test, mockall::automock)]
pub trait NicSysIo: Send + Sync {
    /// Read the full content of `/proc/interrupts`.
    fn read_interrupts(&self) -> Option<String>;

    /// Read `/proc/irq/{irq}/smp_affinity_list`, trimming trailing whitespace.
    fn read_affinity_list(&self, irq: &str) -> Option<String>;

    /// Write `value` to `/proc/irq/{irq}/smp_affinity_list`.
    /// Returns `true` on success.
    fn write_affinity_list(&self, irq: &str, value: &str) -> bool;

    /// Return the names of all `rx-*` entries under
    /// `/sys/class/net/{ifname}/queues/`.
    fn list_rx_queues(&self, ifname: &str) -> Vec<String>;

    /// Read `/sys/class/net/{ifname}/queues/{queue}/rps_cpus`, trimming
    /// trailing whitespace.
    fn read_rps_cpus(&self, ifname: &str, queue: &str) -> Option<String>;

    /// Write `value` to `/sys/class/net/{ifname}/queues/{queue}/rps_cpus`.
    /// Returns `true` on success.
    fn write_rps_cpus(&self, ifname: &str, queue: &str, value: &str) -> bool;
}

/// Production implementation of [`NicSysIo`] that performs real filesystem I/O.
pub struct DefaultNicSysIo;

impl NicSysIo for DefaultNicSysIo {
    fn read_interrupts(&self) -> Option<String> {
        std::fs::read_to_string("/proc/interrupts").ok()
    }

    fn read_affinity_list(&self, irq: &str) -> Option<String> {
        let path = format!("/proc/irq/{irq}/smp_affinity_list");
        std::fs::read_to_string(&path)
            .ok()
            .map(|s| s.trim_end().to_string())
    }

    fn write_affinity_list(&self, irq: &str, value: &str) -> bool {
        let path = format!("/proc/irq/{irq}/smp_affinity_list");
        if let Err(e) = std::fs::write(&path, value) {
            log::warn!("cpu_affinity: could not write {path}: {e}");
            false
        } else {
            true
        }
    }

    fn list_rx_queues(&self, ifname: &str) -> Vec<String> {
        let dir = format!("/sys/class/net/{ifname}/queues");
        match std::fs::read_dir(&dir) {
            Ok(entries) => entries
                .flatten()
                .map(|e| e.file_name().to_string_lossy().into_owned())
                .filter(|n| n.starts_with("rx-"))
                .collect(),
            Err(e) => {
                log::warn!("cpu_affinity: could not read {dir}: {e}");
                vec![]
            }
        }
    }

    fn read_rps_cpus(&self, ifname: &str, queue: &str) -> Option<String> {
        let path = format!("/sys/class/net/{ifname}/queues/{queue}/rps_cpus");
        std::fs::read_to_string(&path)
            .ok()
            .map(|s| s.trim_end().to_string())
    }

    fn write_rps_cpus(&self, ifname: &str, queue: &str, value: &str) -> bool {
        let path = format!("/sys/class/net/{ifname}/queues/{queue}/rps_cpus");
        if let Err(e) = std::fs::write(&path, value) {
            log::warn!("cpu_affinity: could not write {path}: {e}");
            false
        } else {
            true
        }
    }
}

// ---------------------------------------------------------------------------
// NIC IRQ / RPS affinity — apply, capture, restore
// ---------------------------------------------------------------------------

/// Saved IRQ/RPS affinity state for one interface, captured before we changed it.
#[derive(Debug, Clone, Default)]
pub struct NicAffinitySnapshot {
    /// IRQ number string → content of `/proc/irq/{N}/smp_affinity_list` before our change.
    pub irq_lists: HashMap<String, String>,
    /// Queue name (e.g. `"rx-0"`) → content of its `rps_cpus` file before our change.
    pub rps_queues: HashMap<String, String>,
}

/// Per-interface snapshot store with attach/detach reference counting.
///
/// - First `on_attach` for an interface captures the current NIC affinity (ref = 1).
/// - Subsequent `on_attach` calls for the same interface just increment the ref.
/// - `on_detach` decrements the ref; when it hits zero the snapshot is returned for restoration.
/// - `drain_all` removes every interface (used by `detach_all`).
#[derive(Debug, Default)]
pub struct NicAffinityStore {
    inner: HashMap<String, (NicAffinitySnapshot, usize)>,
}

impl NicAffinityStore {
    pub fn new() -> Self {
        Self::default()
    }

    /// Called before applying NIC affinity on attach.
    ///
    /// Captures the current settings on the first attach for this interface
    /// (using `io` to read `/proc` and `/sys`); only increments the ref on
    /// subsequent attaches of the same interface.
    pub fn on_attach(&mut self, ifname: &str, io: &dyn NicSysIo) {
        match self.inner.entry(ifname.to_string()) {
            std::collections::hash_map::Entry::Occupied(mut e) => {
                e.get_mut().1 += 1;
            }
            std::collections::hash_map::Entry::Vacant(v) => {
                let snapshot = capture_nic_affinity(ifname, io);
                v.insert((snapshot, 1));
            }
        }
    }

    /// Called after a successful detach.
    ///
    /// Decrements the ref for `ifname`; when it reaches zero the snapshot is removed
    /// and returned to the caller for restoration.
    pub fn on_detach(&mut self, ifname: &str) -> Option<NicAffinitySnapshot> {
        if let Some(entry) = self.inner.get_mut(ifname) {
            entry.1 = entry.1.saturating_sub(1);
            if entry.1 == 0 {
                return self.inner.remove(ifname).map(|(snap, _)| snap);
            }
        }
        None
    }

    /// Remove all interface snapshots and return them (used by `detach_all`).
    pub fn drain_all(&mut self) -> Vec<(String, NicAffinitySnapshot)> {
        self.inner.drain().map(|(k, (snap, _))| (k, snap)).collect()
    }
}

/// Steer NIC IRQs and software RPS for `ifname` onto `cpus`.
///
/// 1. Parses `/proc/interrupts` for IRQ numbers whose description contains
///    `ifname` and writes a CPU-list string to `/proc/irq/{N}/smp_affinity_list`.
/// 2. Writes a hex CPU-mask to every
///    `/sys/class/net/{ifname}/queues/rx-*/rps_cpus` file (software RPS).
///
/// All failures are logged but never fatal.
pub fn apply_nic_affinity(ifname: &str, cpus: &[usize], io: &dyn NicSysIo) {
    if cpus.is_empty() {
        return;
    }
    let cpu_list = format_cpu_list(cpus);
    let cpu_mask = cpu_list_to_hex_mask(cpus);

    // Hardware IRQ steering
    if let Some(content) = io.read_interrupts() {
        for (irq, _) in irqs_for_iface(&content, ifname) {
            if io.write_affinity_list(&irq, &cpu_list) {
                log::info!("cpu_affinity: IRQ {irq} ({ifname}) → CPUs {cpu_list}");
            }
        }
    } else {
        log::warn!("cpu_affinity: could not read /proc/interrupts");
    }

    // Software RPS
    for queue in io.list_rx_queues(ifname) {
        if io.write_rps_cpus(ifname, &queue, &cpu_mask) {
            log::info!("cpu_affinity: RPS {ifname}/{queue} → mask {cpu_mask}");
        }
    }
}

/// Restore NIC affinity to the state captured in `snapshot`.
///
/// Writes the saved `smp_affinity_list` and `rps_cpus` values back.
/// All failures are logged but never fatal.
pub fn restore_nic_affinity(ifname: &str, snapshot: &NicAffinitySnapshot, io: &dyn NicSysIo) {
    for (irq, original) in &snapshot.irq_lists {
        if io.write_affinity_list(irq, original) {
            log::info!("cpu_affinity: restored IRQ {irq} ({ifname}) → {original}");
        }
    }
    for (queue, original) in &snapshot.rps_queues {
        if io.write_rps_cpus(ifname, queue, original) {
            log::info!("cpu_affinity: restored RPS {ifname}/{queue} → {original}");
        }
    }
}

// ---------------------------------------------------------------------------
// Private: read current NIC affinity into a snapshot
// ---------------------------------------------------------------------------

fn capture_nic_affinity(ifname: &str, io: &dyn NicSysIo) -> NicAffinitySnapshot {
    let mut snapshot = NicAffinitySnapshot::default();

    if let Some(content) = io.read_interrupts() {
        for (irq, _) in irqs_for_iface(&content, ifname) {
            if let Some(val) = io.read_affinity_list(&irq) {
                snapshot.irq_lists.insert(irq, val);
            }
        }
    }

    for queue in io.list_rx_queues(ifname) {
        if let Some(val) = io.read_rps_cpus(ifname, &queue) {
            snapshot.rps_queues.insert(queue, val);
        }
    }

    snapshot
}

/// Parse `/proc/interrupts` content and return `(irq_nr, description)` pairs
/// whose description contains `ifname`.
fn irqs_for_iface<'a>(content: &'a str, ifname: &str) -> impl Iterator<Item = (String, &'a str)> {
    content
        .lines()
        .filter_map(|line| {
            let trimmed = line.trim_start();
            let colon = trimmed.find(':')?;
            let irq = trimmed[..colon].trim().to_string();
            let desc = &trimmed[colon + 1..];
            if desc.contains(ifname) {
                Some((irq, desc))
            } else {
                None
            }
        })
        .collect::<Vec<_>>()
        .into_iter()
}

// ---------------------------------------------------------------------------
// Pure helpers — unit-testable with no OS calls
// ---------------------------------------------------------------------------

/// Convert a CPU list to a compact string suitable for `smp_affinity_list`.
///
/// Consecutive CPUs are collapsed into ranges, non-consecutive are joined with commas.
/// Examples: `[2, 3, 4]` → `"2-4"`, `[0, 2, 4]` → `"0,2,4"`, `[0]` → `"0"`.
fn format_cpu_list(cpus: &[usize]) -> String {
    if cpus.is_empty() {
        return String::new();
    }
    let mut sorted = cpus.to_vec();
    sorted.sort_unstable();
    sorted.dedup();

    let mut parts: Vec<String> = Vec::new();
    let mut range_start = sorted[0];
    let mut range_end = sorted[0];

    for &cpu in &sorted[1..] {
        if cpu == range_end + 1 {
            range_end = cpu;
        } else {
            if range_start == range_end {
                parts.push(range_start.to_string());
            } else {
                parts.push(format!("{range_start}-{range_end}"));
            }
            range_start = cpu;
            range_end = cpu;
        }
    }
    if range_start == range_end {
        parts.push(range_start.to_string());
    } else {
        parts.push(format!("{range_start}-{range_end}"));
    }

    parts.join(",")
}

/// Convert a CPU list to a hex bitmask string (no `0x` prefix) for `rps_cpus`.
///
/// Examples: `[0]` → `"1"`, `[0, 1]` → `"3"`, `[2]` → `"4"`.
fn cpu_list_to_hex_mask(cpus: &[usize]) -> String {
    let mut mask: u64 = 0;
    for &cpu in cpus {
        if cpu < 64 {
            mask |= 1u64 << cpu;
        }
    }
    format!("{mask:x}")
}

#[cfg(test)]
mod tests {
    use mockall::predicate::*;

    use super::*;

    // -----------------------------------------------------------------------
    // Pure helpers
    // -----------------------------------------------------------------------

    #[test]
    fn test_format_cpu_list_single() {
        assert_eq!(format_cpu_list(&[0]), "0");
    }

    #[test]
    fn test_format_cpu_list_range() {
        assert_eq!(format_cpu_list(&[2, 3, 4]), "2-4");
    }

    #[test]
    fn test_format_cpu_list_non_consecutive() {
        assert_eq!(format_cpu_list(&[0, 2, 4]), "0,2,4");
    }

    #[test]
    fn test_format_cpu_list_mixed() {
        assert_eq!(format_cpu_list(&[0, 1, 3, 4, 5]), "0-1,3-5");
    }

    #[test]
    fn test_format_cpu_list_empty() {
        assert_eq!(format_cpu_list(&[]), "");
    }

    #[test]
    fn test_cpu_list_to_hex_mask_zero() {
        assert_eq!(cpu_list_to_hex_mask(&[0]), "1");
    }

    #[test]
    fn test_cpu_list_to_hex_mask_two() {
        assert_eq!(cpu_list_to_hex_mask(&[0, 1]), "3");
    }

    #[test]
    fn test_cpu_list_to_hex_mask_bit2() {
        assert_eq!(cpu_list_to_hex_mask(&[2]), "4");
    }

    #[test]
    fn test_cpu_list_to_hex_mask_multi() {
        // CPUs 2 and 3 → bits 2,3 → 0b1100 = 0xc
        assert_eq!(cpu_list_to_hex_mask(&[2, 3]), "c");
    }

    #[test]
    fn test_cpu_list_to_hex_mask_empty() {
        assert_eq!(cpu_list_to_hex_mask(&[]), "0");
    }

    #[test]
    fn test_irqs_for_iface_filters_correctly() {
        let content = "\
  42:   1234   PCI-MSI  eth0-TxRx-0\n\
  43:    567   PCI-MSI  eth1-TxRx-0\n\
  44:    890   PCI-MSI  eth0-TxRx-1\n\
 ERR:      0\n";
        let matches: Vec<_> = irqs_for_iface(content, "eth0").collect();
        assert_eq!(matches.len(), 2);
        assert_eq!(matches[0].0, "42");
        assert_eq!(matches[1].0, "44");
    }

    #[test]
    fn test_irqs_for_iface_no_match() {
        let content = "  10:   100   PCI-MSI  eth1-rx\n";
        let matches: Vec<_> = irqs_for_iface(content, "eth0").collect();
        assert!(matches.is_empty());
    }

    // -----------------------------------------------------------------------
    // apply_nic_affinity
    // -----------------------------------------------------------------------

    /// IRQ whose description contains the interface name gets steered; one that
    /// doesn't is left alone.  RPS queue also gets the correct hex mask.
    #[test]
    fn test_apply_writes_matching_irq_and_rps() {
        let mut mock = MockNicSysIo::new();

        mock.expect_read_interrupts().once().returning(|| {
            Some(
                "  42:   0   PCI-MSI  eth0-TxRx-0\n\
                 43:   0   PCI-MSI  eth1-TxRx-0\n"
                    .to_string(),
            )
        });

        // Only IRQ 42 matches "eth0"; IRQ 43 must never be written.
        mock.expect_write_affinity_list()
            .with(eq("42"), eq("2-3"))
            .once()
            .returning(|_, _| true);

        mock.expect_list_rx_queues()
            .with(eq("eth0"))
            .once()
            .returning(|_| vec!["rx-0".to_string()]);

        // CPUs [2,3] → mask = bits 2+3 = 0b1100 = 0xc
        mock.expect_write_rps_cpus()
            .with(eq("eth0"), eq("rx-0"), eq("c"))
            .once()
            .returning(|_, _, _| true);

        apply_nic_affinity("eth0", &[2, 3], &mock);
    }

    /// When /proc/interrupts contains no matching IRQ, no writes happen.
    #[test]
    fn test_apply_no_matching_irq() {
        let mut mock = MockNicSysIo::new();

        mock.expect_read_interrupts()
            .once()
            .returning(|| Some("  10:   0   PCI-MSI  eth1-TxRx-0\n".to_string()));

        // No affinity writes expected — mockall will fail the test if any occur.
        mock.expect_list_rx_queues()
            .with(eq("eth0"))
            .once()
            .returning(|_| vec![]);

        apply_nic_affinity("eth0", &[0], &mock);
    }

    /// Empty `cpus` slice → no IO at all.
    #[test]
    fn test_apply_empty_cpu_list_is_noop() {
        let mock = MockNicSysIo::new();
        // No expectations set — any call would panic.
        apply_nic_affinity("eth0", &[], &mock);
    }

    // -----------------------------------------------------------------------
    // capture_nic_affinity (tested indirectly via NicAffinityStore::on_attach)
    // -----------------------------------------------------------------------

    /// on_attach reads current IRQ and RPS values; on_detach returns them.
    #[test]
    fn test_capture_reads_irq_and_rps() {
        let mut mock = MockNicSysIo::new();

        mock.expect_read_interrupts()
            .once()
            .returning(|| Some("  55:   0   PCI-MSI  eth0-rx\n".to_string()));
        mock.expect_read_affinity_list()
            .with(eq("55"))
            .once()
            .returning(|_| Some("0-3".to_string()));
        mock.expect_list_rx_queues()
            .with(eq("eth0"))
            .once()
            .returning(|_| vec!["rx-0".to_string()]);
        mock.expect_read_rps_cpus()
            .with(eq("eth0"), eq("rx-0"))
            .once()
            .returning(|_, _| Some("f".to_string()));

        let mut store = NicAffinityStore::new();
        store.on_attach("eth0", &mock);

        let snap = store
            .on_detach("eth0")
            .expect("snapshot should be returned");
        assert_eq!(snap.irq_lists.get("55").map(String::as_str), Some("0-3"));
        assert_eq!(snap.rps_queues.get("rx-0").map(String::as_str), Some("f"));
    }

    /// When /proc/interrupts is unreadable the snapshot is empty (no panic).
    #[test]
    fn test_capture_handles_missing_proc_interrupts() {
        let mut mock = MockNicSysIo::new();

        mock.expect_read_interrupts().once().returning(|| None);
        mock.expect_list_rx_queues()
            .with(eq("eth0"))
            .once()
            .returning(|_| vec![]);

        let mut store = NicAffinityStore::new();
        store.on_attach("eth0", &mock);

        let snap = store.on_detach("eth0").unwrap();
        assert!(snap.irq_lists.is_empty());
        assert!(snap.rps_queues.is_empty());
    }

    // -----------------------------------------------------------------------
    // restore_nic_affinity
    // -----------------------------------------------------------------------

    #[test]
    fn test_restore_writes_back_saved_values() {
        let mut mock = MockNicSysIo::new();

        mock.expect_write_affinity_list()
            .with(eq("42"), eq("0-3"))
            .once()
            .returning(|_, _| true);

        mock.expect_write_rps_cpus()
            .with(eq("eth0"), eq("rx-0"), eq("f"))
            .once()
            .returning(|_, _, _| true);

        let snap = NicAffinitySnapshot {
            irq_lists: [("42".to_string(), "0-3".to_string())].into(),
            rps_queues: [("rx-0".to_string(), "f".to_string())].into(),
        };

        restore_nic_affinity("eth0", &snap, &mock);
    }

    /// restore on an empty snapshot does nothing.
    #[test]
    fn test_restore_empty_snapshot_is_noop() {
        let mock = MockNicSysIo::new();
        restore_nic_affinity("eth0", &NicAffinitySnapshot::default(), &mock);
    }

    // -----------------------------------------------------------------------
    // NicAffinityStore ref-counting
    // -----------------------------------------------------------------------

    // Helper: build a mock that expects one capture call for eth0.
    fn mock_capture_eth0(irq: &'static str, queue: &'static str) -> MockNicSysIo {
        let mut mock = MockNicSysIo::new();
        let irq_line = format!("  {irq}:   0   PCI-MSI  eth0-rx\n");
        mock.expect_read_interrupts()
            .once()
            .returning(move || Some(irq_line.clone()));
        mock.expect_read_affinity_list()
            .once()
            .returning(|_| Some("0-7".to_string()));
        mock.expect_list_rx_queues()
            .with(eq("eth0"))
            .once()
            .returning(move |_| vec![queue.to_string()]);
        mock.expect_read_rps_cpus()
            .once()
            .returning(|_, _| Some("ff".to_string()));
        mock
    }

    #[test]
    fn test_single_attach_detach_returns_snapshot() {
        let mock = mock_capture_eth0("10", "rx-0");
        let mut store = NicAffinityStore::new();
        store.on_attach("eth0", &mock);
        let snap = store.on_detach("eth0");
        assert!(snap.is_some());
        assert!(store.inner.is_empty());
    }

    #[test]
    fn test_double_attach_captures_only_once() {
        // mock_capture_eth0 uses `.once()` — a second capture would panic.
        let mock = mock_capture_eth0("10", "rx-0");
        let mut store = NicAffinityStore::new();
        store.on_attach("eth0", &mock);
        // Second attach: mock has no more expectations, so no IO calls expected.
        let mock2 = MockNicSysIo::new();
        store.on_attach("eth0", &mock2);
        assert_eq!(store.inner["eth0"].1, 2);
    }

    #[test]
    fn test_double_attach_needs_two_detaches() {
        let mock = mock_capture_eth0("10", "rx-0");
        let mut store = NicAffinityStore::new();
        store.on_attach("eth0", &mock);
        let mock2 = MockNicSysIo::new();
        store.on_attach("eth0", &mock2);

        // First detach: ref 2→1, no snapshot yet.
        assert!(store.on_detach("eth0").is_none());
        assert_eq!(store.inner["eth0"].1, 1);

        // Second detach: ref 1→0, snapshot returned.
        assert!(store.on_detach("eth0").is_some());
        assert!(store.inner.is_empty());
    }

    #[test]
    fn test_detach_unknown_interface_is_noop() {
        let mut store = NicAffinityStore::new();
        assert!(store.on_detach("eth99").is_none());
    }

    #[test]
    fn test_drain_all_returns_all_interfaces() {
        let mock_a = mock_capture_eth0("10", "rx-0");
        let mut mock_b = MockNicSysIo::new();
        let irq_line = "  11:   0   PCI-MSI  eth1-rx\n".to_string();
        mock_b
            .expect_read_interrupts()
            .once()
            .returning(move || Some(irq_line.clone()));
        mock_b
            .expect_read_affinity_list()
            .once()
            .returning(|_| Some("0-7".to_string()));
        mock_b.expect_list_rx_queues().once().returning(|_| vec![]);

        let mut store = NicAffinityStore::new();
        store.on_attach("eth0", &mock_a);
        store.on_attach("eth1", &mock_b);

        let drained = store.drain_all();
        assert_eq!(drained.len(), 2);
        assert!(store.inner.is_empty());
    }
}
